name: Cleanup merged branches

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 0'

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const main = 'main'
            const per_page = 100
            let page = 1
            const branches = []
            while (true) {
              const { data } = await github.rest.repos.listBranches({ owner: context.repo.owner, repo: context.repo.repo, per_page, page })
              if (!data.length) break
              branches.push(...data)
              page++
            }
            for (const br of branches) {
              const name = br.name
              if (name === main) continue
              if (br.protected) continue
              try {
                const cmp = await github.rest.repos.compareCommits({ owner: context.repo.owner, repo: context.repo.repo, base: name, head: main })
                if (cmp.data.status === 'identical' || cmp.data.status === 'behind') {
                  await github.rest.git.deleteRef({ owner: context.repo.owner, repo: context.repo.repo, ref: `heads/${name}` })
                  core.info(`Deleted ${name}`)
                } else {
                  core.info(`Keeping ${name} (status ${cmp.data.status})`)
                }
              } catch (e) {
                core.warning(`Skipping ${br.name}: ${e.message}`)
              }
            }
