name: Deploy to Cloud Run from Source (IDV)

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  SERVICE: ${{ secrets.CLOUD_RUN_SERVICE_IDV || 'idv' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER
 }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          project_id: ${{ env.PROJECT_ID }}

      - id: deploy
        name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          source: ./services/idv
          allow_unauthenticated: true
          env_vars: |
            FACE_SIMILARITY_MIN=0.65
          flags: |
            --memory=2Gi
            --cpu=2
            --min-instances=0
            --max-instances=3

      - name: Show Cloud Run URL
        run: echo Cloud_Run_URL=${{ steps.deploy.outputs.url }}
