# .github/workflows/qualitylab.yml (dbaitr)
name: Quality Lab

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  qualitylab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Quality Lab
        uses: georgioskroupis/quality-lab@v1
        with:
          fail-on: high
          comment-pr: true
          lighthouse-url: https://dbaitr.com
