name: Quality Lab – Full Scan (Report Only)

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  fullscan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Quality Lab (full repo, non-blocking)
        uses: georgioskroupis/quality-lab@v1
        with:
          fail-on: none               # never fail; always produce report
          comment-pr: false
          lighthouse-url: https://dbaitr.com
