name: Update Transparency Metrics

on:
  schedule:
    - cron: '17 2 * * *' # every day at 02:17 UTC
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Prepare service account (raw JSON)
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          if [ -n "${FIREBASE_SERVICE_ACCOUNT}" ]; then
            echo "Writing service account to runner temp..."
            printf "%s" "${FIREBASE_SERVICE_ACCOUNT}" > "$RUNNER_TEMP/sa.json"
            echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/sa.json" >> "$GITHUB_ENV"
          else
            echo "No raw JSON secret provided; relying on B64 or ADC."
          fi

      - name: Run transparency update
        env:
          FIREBASE_SERVICE_ACCOUNT_B64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_B64 }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node scripts/ops/update-transparency.mjs
